name: Scheduled check for alerts in Hypothesis org
on:
  schedule:
    - cron: '30 10 * * 1'
  workflow_dispatch:
jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip install --upgrade pipenv
          pipenv install --deploy

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install gha-token
        run: python -m pipx install "git+https://github.com/hypothesis/gha-token.git"

      - name: Get GitHub token
        id: github_token
        run: echo GITHUB_TOKEN=$(gha-token --app-id 274948 --installation-id 32440510 --private-key "$PRIVATE_KEY") >> $GITHUB_OUTPUT
        env:
          PRIVATE_KEY: ${{ secrets.HYPOTHESIS_GITHUB_APP_PRIVATE_KEY }}

      - name: Check for alerts
        env:
          GITHUB_TOKEN: ${{ steps.github_token.outputs.GITHUB_TOKEN }}
          SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_DEPENDABOT_ALERT_TOKEN }}
        run: |
          pipenv run alerts hypothesis --slack
