name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip install --upgrade pipenv
          pipenv install --dev --deploy

      - name: QA
        run: |
          pipenv run qa

      - name: Dry run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Do a dry-run of the tool. This will query for PRs but simulate
          # the user entering "skip" for each one.
          pipenv run review hypothesis
