name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install --upgrade poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: QA
        run: |
          make qa

      - name: Dry run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Do a dry-run of the tool. This will query for PRs but simulate
          # the user entering "skip" for each one.
          ./review.sh hypothesis
